/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cordis.UI;

import Cordis.DB.DatabaseConnectivity;
import Cordis.DB.GetEntities;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhoet
 */
public class ExperimentalBalti extends javax.swing.JFrame {
    
    private static GetEntities projectDB = new GetEntities();
     private static DatabaseConnectivity connect = new DatabaseConnectivity();

    /**
     * Creates new form ExperimentalBalti
     */
    public ExperimentalBalti() {
        
        initComponents();
         
        JButton Searchbttn = new JButton("Search");

        
        
        //DISPLAY COMPOUND TABLE
        //Query to be executed
        
        String query = "";
        
        query = "SELECT *  FROM Project ;";
        
        //Creates list of Lists 
        List<List<String>> list = connect.readDatabase(query, true);
        
        //Creates Array of Columns names
        String [] nameOfCompoundCategories = new String [list.get(1).size()];
        //Populating Array Of Columns Names 
        for(int n = 0; n<list.get(0).size(); n++){
            nameOfCompoundCategories [n] = list.get(0).get(n);
        }
        
        Object[][] compoundData = new String[list.size()-1][list.get(1).size()];
        for(int l = 1; l<list.size(); l++){
            for(int r = 0; r<list.get(l).size(); r++){
                compoundData [l-1] [r] = list.get(l).get(r);
            }
            
        } 
            
        System.out.println("[JFrame] ... Displaying JTable, List of Columns");
        DefaultTableModel compoundModel = (DefaultTableModel) TableBalti.getModel();
        compoundModel.setDataVector(compoundData,nameOfCompoundCategories); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBalti = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        Label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableBalti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableBalti);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label1.setText("Search by Title:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

        String text = jTextField1.getText();

        //DISPLAY COMPOUND TABLE
        //Query to be executed

        String query = "";

        query = "SELECT  * FROM Project WHERE proTitle  LIKE '%"+text+"%';";;

        //Creates list of Lists
        List<List<String>> list = connect.readDatabase(query, true);

        //Creates Array of Columns names
        String [] nameOfCompoundCategories = new String [list.get(1).size()];
        //Populating Array Of Columns Names
        for(int n = 0; n<list.get(0).size(); n++){
            nameOfCompoundCategories [n] = list.get(0).get(n);
        }

        Object[][] compoundData = new String[list.size()-1][list.get(1).size()];
        for(int l = 1; l<list.size(); l++){
            for(int r = 0; r<list.get(l).size(); r++){
                compoundData [l-1] [r] = list.get(l).get(r);
            }

        }

        System.out.println("[JFrame] ... Displaying JTable, List of Columns");
        DefaultTableModel compoundModel = (DefaultTableModel) TableBalti.getModel();
        compoundModel.setDataVector(compoundData,nameOfCompoundCategories);
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExperimentalBalti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExperimentalBalti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExperimentalBalti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExperimentalBalti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExperimentalBalti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Label1;
    private javax.swing.JTable TableBalti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
