/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
* hello it's Mhanaj
 */
package Cordis.UI;

import Cordis.DB.DatabaseConnectivity;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author hossa
 */
public class LogPage extends javax.swing.JFrame {

    /**
     * Creates new form LogPage
     */
    public LogPage() {
        initComponents();
        System.out.println("[LogPage] ... isConnected");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameT = new javax.swing.JTextField();
        PasswordT = new javax.swing.JPasswordField();
        signInLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 19, 65));

        UsernameT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        UsernameT.setForeground(new java.awt.Color(153, 153, 153));
        UsernameT.setText("Email");
        UsernameT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameTFocusLost(evt);
            }
        });
        UsernameT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTActionPerformed(evt);
            }
        });

        PasswordT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PasswordT.setForeground(new java.awt.Color(153, 153, 153));
        PasswordT.setText("password");
        PasswordT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordTFocusLost(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 153, 102));
        signInLabel.setText("Sign In");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("or");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        signUpLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpLabel.setText("Sign Up");
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(signInLabel)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(signUpLabel)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordT, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(UsernameT, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(743, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInLabel)
                    .addComponent(jLabel2)
                    .addComponent(signUpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFocusGained
        //disapear text when clicked

        if(UsernameT.getText().trim().toLowerCase().equals("email"))
        {
            UsernameT.setText("");
            UsernameT.setForeground(java.awt.Color.black);
        }

    }//GEN-LAST:event_UsernameTFocusGained

    private void UsernameTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTFocusLost
        //"email" or empt
        if(UsernameT.getText().trim().equals("")||
            UsernameT.getText().trim().toLowerCase().equals("email"))
        {
            UsernameT.setText("Email");
            UsernameT.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_UsernameTFocusLost

    private void PasswordTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTFocusGained
        //disapear text when clicked PASSWORD

        String password = String.valueOf(PasswordT.getPassword());
        //System.out.println(password);
        if(password.trim().toLowerCase().equals("password"))
        {
            //System.out.println("test");
            PasswordT.setText("");
            PasswordT.setForeground(java.awt.Color.black);
        }
        //System.out.println("test2");

    }//GEN-LAST:event_PasswordTFocusGained

    private void PasswordTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTFocusLost

        String password = String.valueOf(PasswordT.getPassword());
        if(password.trim().equals("") ||
            password.trim().toLowerCase().equals("password"))
        {
            PasswordT.setText("password");
            PasswordT.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_PasswordTFocusLost

    
    /**
     * Submit method, SIGN IN USER 
     * @param evt action on click
     */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        System.out.println("[LogPage] ... Login Process");
        
        //Scan Input
        String username = UsernameT.getText();
        String password = String.valueOf(PasswordT.getPassword());
        
        //if user did not fill up any 
        if (username.equals("Email") || password.equals("password")){
         
            System.out.println("[LogPage] ... Please, fill in all required fields!");
            
            JOptionPane.showMessageDialog(null, "Please, fill in all required fields!", "Required Fields", JOptionPane.WARNING_MESSAGE);
            
        //if entered all mandatory fiels, program will query data
        }else{
            
            System.out.println("[LogPage] ... Connecting User Database");
            
            DatabaseConnectivity databaseConnectivity = new DatabaseConnectivity("jdbc:sqlite:Users.sqlite3");
            
            String SQL = "SELECT userType, userForename, userSurname, userEmail, userPassword "
                        +"FROM Users "
                        +"WHERE userEmail LIKE '"+username+"'";
            
            List<List<String>> list = databaseConnectivity.readDatabase(SQL, false);
            
            if(list.size() == 0){
                
                System.out.println("[LogPage] ... Username not found. Please Enter Valid Username or Sign Up");
                
                JOptionPane.showMessageDialog(null, "Please enter valid Username or Sign Up.", "Username not found", JOptionPane.WARNING_MESSAGE);
                
            }else{
                String userType = list.get(0).get(0);
                String userForename = list.get(0).get(1);
                String userSurname = list.get(0).get(2);
                String userEmail = list.get(0).get(3);
                String userPassword = list.get(0).get(4);
             
                if(userPassword.equals(password) &&  userType.equals("U")){
                    System.out.println("[LogPage] ... Welcome User "+userForename+" "+userSurname);
                    
                    //String Message = "Welcome User "+userForename+" "+userSurname;
                    //JOptionPane.showMessageDialog(null, Message);
                    
                    Dashboard dash = new Dashboard();
                    dash.setVisible(true);
                    dash.pack();
                    dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    
                }else if (userPassword.equals(password) &&  userType.equals("A")){
                    System.out.println("[LogPage] ... Welcome Administrator");
                
                    JOptionPane.showMessageDialog(null,  "Welcome Administrator");
                    
                    UserActivity ua = new UserActivity();
                    ua.setVisible(true);
                    ua.pack();
                    ua.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    
                }else{
                
                    System.out.println("[LogPage] ... Incorrect Password. Please Enter Correct Password or choose Forgotten Password");
                    
                    JOptionPane.showMessageDialog(null,
                                                "Please Enter Correct Password or choose Forgotten Password.",
                                                "Incorrect Password",
                                                JOptionPane.ERROR_MESSAGE);
                }
            }
                 
        }
        
        
//        LukasPart reg = new LukasPart();
//        reg.setVisible(true);
//        reg.pack();
//        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();
        
        
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        //TODO add your handling code here:
        RegPage reg = new RegPage();
        reg.setVisible(true);
        reg.pack();
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void signUpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        signUpLabel.setBorder(label_border);
    }//GEN-LAST:event_signUpLabelMouseEntered

    private void signUpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseExited
        signUpLabel.setBorder(null);
    }//GEN-LAST:event_signUpLabelMouseExited

    private void UsernameTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordT;
    private javax.swing.JTextField UsernameT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
