/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cordis.UI;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author hossa
 */
public class UserActivity extends javax.swing.JFrame {

    /**
     * Creates new form UserActivity
     */
    public UserActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        adminSign = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        usernameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        userActivitySign = new javax.swing.JLabel();
        userActSign = new javax.swing.JLabel();
        userDetSign = new javax.swing.JLabel();
        logOutSign = new javax.swing.JLabel();
        dashboardTab = new javax.swing.JLabel();
        filter = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        logoLabel.setBackground(new java.awt.Color(0, 0, 0));

        adminSign.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        adminSign.setForeground(new java.awt.Color(255, 153, 102));
        adminSign.setText("ADMIN PAGE");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        usernameField.setText("USERNAME");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Log In", "Log Out", "Duration"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        userActivitySign.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        userActivitySign.setForeground(new java.awt.Color(255, 153, 102));
        userActivitySign.setText("USER ACTIVITY BOARD");

        userActSign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userActSign.setForeground(new java.awt.Color(255, 153, 102));
        userActSign.setText("USER ACTIVITY BOARD");

        userDetSign.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userDetSign.setForeground(new java.awt.Color(204, 204, 204));
        userDetSign.setText("USER DETAILS");
        userDetSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDetSignMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userDetSignMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userDetSignMouseEntered(evt);
            }
        });

        logOutSign.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        logOutSign.setForeground(new java.awt.Color(204, 204, 204));
        logOutSign.setText("LOG OUT");
        logOutSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutSignMouseExited(evt);
            }
        });

        dashboardTab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dashboardTab.setForeground(new java.awt.Color(204, 204, 204));
        dashboardTab.setText("DASHBOARD");
        dashboardTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardTabMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardTabMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardTabMouseEntered(evt);
            }
        });

        filter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminSign)
                        .addGap(439, 439, 439)
                        .addComponent(userActivitySign)
                        .addGap(0, 512, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dashboardTab)
                                .addGap(18, 18, 18)
                                .addComponent(userActSign)
                                .addGap(18, 18, 18)
                                .addComponent(userDetSign)
                                .addGap(18, 18, 18)
                                .addComponent(logOutSign)
                                .addGap(638, 638, 638)
                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminSign)
                            .addComponent(userActivitySign))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userActSign)
                    .addComponent(userDetSign)
                    .addComponent(logOutSign)
                    .addComponent(dashboardTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        //set icon to jlabel
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DashboardLogom.png")));
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 102));
        userActivitySign.setBorder(label_border);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void userDetSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMouseExited
        // TODO add your handling code here:
        userDetSign.setBorder(null);
    }//GEN-LAST:event_userDetSignMouseExited

    private void userDetSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        userDetSign.setBorder(label_border);
    }//GEN-LAST:event_userDetSignMouseEntered

    private void userDetSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMouseClicked
        // TODO add your handling code here:
        UserDetails userD = new UserDetails();
        userD.setVisible(true);
        userD.pack();
        userD.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_userDetSignMouseClicked

    private void logOutSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMouseClicked
        // TODO add your handling code here:
        LogPage logp = new LogPage();
        logp.setVisible(true);
        logp.pack();
        logp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logOutSignMouseClicked

    private void logOutSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        logOutSign.setBorder(label_border);        
    }//GEN-LAST:event_logOutSignMouseEntered

    private void logOutSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMouseExited
        // TODO add your handling code here:
         logOutSign.setBorder(null);
    }//GEN-LAST:event_logOutSignMouseExited

    private void dashboardTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMouseExited
        // TODO add your handling code here:
        dashboardTab.setBorder(null);
    }//GEN-LAST:event_dashboardTabMouseExited

    private void dashboardTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        dashboardTab.setBorder(label_border); 
    }//GEN-LAST:event_dashboardTabMouseEntered

    private void dashboardTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMouseClicked
        // TODO add your handling code here:
        Dashboard das = new Dashboard();
        das.setVisible(true);
        das.pack();
        das.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_dashboardTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminSign;
    private javax.swing.JLabel dashboardTab;
    private javax.swing.JComboBox filter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logOutSign;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel userActSign;
    private javax.swing.JLabel userActivitySign;
    private javax.swing.JLabel userDetSign;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
