/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cordis.UI;

import Cordis.BG.UserLog;
import Cordis.DB.DatabaseConnectivity;
import Cordis.Entities.User;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author lukaskopecky
 */
public class UserActivity extends javax.swing.JFrame {
    
    User localUser;
    private static DatabaseConnectivity connect = new DatabaseConnectivity("jdbc:sqlite:Users.sqlite3");

    /**
     * Creates new form UserActivity
     */
    public UserActivity() {
        initComponents();
        
        this.localUser = null;
        
        //view default table input
        defaultTable();
    }
    
    
    
    /**
     * Constructor in use if accessed form program, displays data
     * @param localUser user displaying the page 
     */
    UserActivity(User localUser) {
        initComponents();
        this.localUser = localUser;
        usernameField.setText(localUser.getName()+" "+localUser.getSurname());
        
        
        UserLog log = new UserLog(localUser);
        log.logActivity("User Activity");
        
        //view defautl table input
        defaultTable();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminSign = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        userActivitySign = new javax.swing.JLabel();
        userActSign = new javax.swing.JLabel();
        userDetSign = new javax.swing.JLabel();
        logOutSign = new javax.swing.JLabel();
        dashboardTab = new javax.swing.JLabel();
        searchUsernameField = new javax.swing.JTextField();
        surnameSearchLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        footerLab = new javax.swing.JLabel();
        fotterLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1680, 990));
        jPanel1.setPreferredSize(new java.awt.Dimension(1680, 900));

        adminSign.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        adminSign.setForeground(new java.awt.Color(255, 153, 102));
        adminSign.setText("CORDIS ");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        userTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Log In", "Log Out", "Duration"
            }
        ));
        userTable.setRowHeight(18);
        jScrollPane1.setViewportView(userTable);

        userActivitySign.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        userActivitySign.setForeground(new java.awt.Color(255, 153, 102));
        userActivitySign.setText("Administrator - USER ACTIVITY BOARD");

        userActSign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userActSign.setForeground(new java.awt.Color(255, 153, 102));
        userActSign.setText("USER ACTIVITY BOARD");

        userDetSign.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userDetSign.setForeground(new java.awt.Color(204, 204, 204));
        userDetSign.setText("USER DETAILS");
        userDetSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userDetSignMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userDetSignMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userDetSignMouseEntered(evt);
            }
        });

        logOutSign.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        logOutSign.setForeground(new java.awt.Color(204, 204, 204));
        logOutSign.setText("LOG OUT");
        logOutSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logOutSignMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutSignMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutSignMouseEntered(evt);
            }
        });

        dashboardTab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dashboardTab.setForeground(new java.awt.Color(204, 204, 204));
        dashboardTab.setText("DASHBOARD");
        dashboardTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardTabMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardTabMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardTabMouseEntered(evt);
            }
        });

        searchUsernameField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        searchUsernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchUsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserActivity.this.keyReleased(evt);
            }
        });

        surnameSearchLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        surnameSearchLabel1.setForeground(new java.awt.Color(204, 204, 204));
        surnameSearchLabel1.setText("SEARCH");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        footerLab.setForeground(new java.awt.Color(255, 153, 102));
        footerLab.setText("Created by Group 4 ");

        fotterLabel.setForeground(new java.awt.Color(153, 153, 153));
        fotterLabel.setText("Members: Lukas Kopecky (w1701833) - Mhanaj Hossain (w1679296) - Md Reyad (w1689489) - Balthasar Hoettges (w1710494)");

        usernameField.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        usernameField.setForeground(new java.awt.Color(204, 204, 204));
        usernameField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameField.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userActSign)
                                .addGap(18, 18, 18)
                                .addComponent(userDetSign)
                                .addGap(18, 18, 18)
                                .addComponent(dashboardTab)
                                .addGap(856, 856, 856)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logOutSign))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(surnameSearchLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(searchUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adminSign)
                                .addGap(415, 415, 415)
                                .addComponent(userActivitySign))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(775, 775, 775)
                                .addComponent(footerLab)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(fotterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(adminSign))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userActivitySign)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameField)
                            .addComponent(logOutSign))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userActSign)
                            .addComponent(userDetSign)
                            .addComponent(dashboardTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameSearchLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fotterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 102));
        userActivitySign.setBorder(label_border);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DashboardLogom.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userDetSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMouseExited
        // TODO add your handling code here:
        userDetSign.setBorder(null);
    }//GEN-LAST:event_userDetSignMouseExited

    private void userDetSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        userDetSign.setBorder(label_border);
    }//GEN-LAST:event_userDetSignMouseEntered

    private void dashboardTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMouseExited
        // TODO add your handling code here:
        dashboardTab.setBorder(null);
    }//GEN-LAST:event_dashboardTabMouseExited

    private void dashboardTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        dashboardTab.setBorder(label_border); 
    }//GEN-LAST:event_dashboardTabMouseEntered

    /**
     * Filtering users
     * @param evt on key released
     */
    private void keyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleased
       
       
       String query;
       String searchFor = searchUsernameField.getText();
        
       //Creating Query
        query = "SELECT u.userEmail as Username,  u.userSurname as Surname, u.userForename as Forename, "
                + "u.userType as \"User Type\", a.logTime as Time, a.logType as \"Log Type\" \n" 
                + "FROM ActivityLog a JOIN Users u "
                + "ON a.userID = u.userID "
                + "AND (u.userEmail LIKE '%"+searchFor+"%'"
                + "OR u.userForename LIKE '%"+searchFor+"%'"
                + "OR u.userSurname LIKE '%"+searchFor+"%');";
        
        //Executing query and displayind data
        List<List<String>> list = connect.readDatabase(query, true);
       
        if(list.size() > 1){
       
            //Creates Array of Columns names
            String [] nameOfCompoundCategories = new String [list.get(1).size()];
            //Populating Array Of Columns Names 
            for(int n = 0; n<list.get(0).size(); n++){
                nameOfCompoundCategories [n] = list.get(0).get(n);
            }

            //loading data
            Object[][] compoundData = new String[list.size()-1][list.get(1).size()];
            for(int l = 1; l<list.size(); l++){
                for(int r = 0; r<list.get(l).size(); r++){
                    if(r == 3){
                        String type = list.get(l).get(r);
                        if(type.equals("A"))
                            compoundData [l-1] [r] = "Administrator";
                        else
                            compoundData [l-1] [r] = "User";

                    }else{
                        compoundData [l-1] [r] = list.get(l).get(r);
                    }


                }

            } 

            //updading table
            System.out.println("[JFrame] ... Displaying JTable, List of Columns");
            DefaultTableModel compoundModel = (DefaultTableModel) userTable.getModel();
            compoundModel.setDataVector(compoundData,nameOfCompoundCategories);
          
        //if keyword was not found    
        }else{
           
            String message = searchFor+" not Found";
           
            JOptionPane.showMessageDialog(null, message,
                        "Key Word Not Found", JOptionPane.WARNING_MESSAGE);
           
            searchUsernameField.setText(null);
           
           
            defaultTable();
           
       }
       
    }//GEN-LAST:event_keyReleased

    private void logOutSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMouseExited
        // TODO add your handling code here:
        logOutSign.setBorder(null);
    }//GEN-LAST:event_logOutSignMouseExited

    private void logOutSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 153, 102));
        logOutSign.setBorder(label_border);
    }//GEN-LAST:event_logOutSignMouseEntered

    private void logOutSignMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutSignMousePressed
        // TODO add your handling code here:
        
        UserLog log = new UserLog(localUser);
        log.logOut();

        LogPage logp = new LogPage();
        logp.setVisible(true);
        logp.pack();
        logp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logOutSignMousePressed

    private void dashboardTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTabMousePressed
        // TODO add your handling code here:
        
        
        
        Dashboard das = new Dashboard(localUser);
        das.setVisible(true);
        das.pack();
        das.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_dashboardTabMousePressed

    private void userDetSignMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetSignMousePressed
        // TODO add your handling code here:
        
        
        UserDetails userD = new UserDetails(localUser);
        userD.setVisible(true);
        userD.pack();
        userD.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_userDetSignMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserActivity().setVisible(true);
            }
        });
    }
    
    /**
     * Displaying default table view
     */
    public final void defaultTable(){
        //Intialise default query
        String query = "SELECT u.userEmail as Username,  u.userSurname as Surname, u.userForename as Forename, "
                + "u.userType as \"User Type\", a.logTime as Time, a.logType as \"Log Type\" \n" 
                + "FROM ActivityLog a JOIN Users u "
                + "ON a.userID = u.userID;";
        
        //Creates list of Lists 
        List<List<String>> list = connect.readDatabase(query, true);
        
        //Creates Array of Columns names
        String [] nameOfCompoundCategories = new String [list.get(1).size()];
        //Populating Array Of Columns Names 
        for(int n = 0; n<list.get(0).size(); n++){
            nameOfCompoundCategories [n] = list.get(0).get(n);
        }
        
        //loading data
        Object[][] compoundData = new String[list.size()-1][list.get(1).size()];
        for(int l = 1; l<list.size(); l++){
            for(int r = 0; r<list.get(l).size(); r++){
                if(r == 3){
                    String type = list.get(l).get(r);
                    if(type.equals("A"))
                        compoundData [l-1] [r] = "Administrator";
                    else
                        compoundData [l-1] [r] = "User";
                    
                }else{
                    compoundData [l-1] [r] = list.get(l).get(r);
                }
                
                
            }
            
        } 
            
        //updating table
        System.out.println("[JFrame] ... Displaying JTable, List of Columns");
        DefaultTableModel compoundModel = (DefaultTableModel) userTable.getModel();
        compoundModel.setDataVector(compoundData,nameOfCompoundCategories); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminSign;
    private javax.swing.JLabel dashboardTab;
    private javax.swing.JLabel footerLab;
    private javax.swing.JLabel fotterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logOutSign;
    private javax.swing.JTextField searchUsernameField;
    private javax.swing.JLabel surnameSearchLabel1;
    private javax.swing.JLabel userActSign;
    private javax.swing.JLabel userActivitySign;
    private javax.swing.JLabel userDetSign;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel usernameField;
    // End of variables declaration//GEN-END:variables
}
